/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home;

import Classes.Dados;
import Classes.Doenca;

/**
 *
 * @author marcelo_eger
 */
public class BotaoCalc2 extends javax.swing.JInternalFrame {

    /**
     * Creates new form Calculos
     */
    public BotaoCalc2() {
        initComponents();
        setSize(650, 400);

    }

    private void add() {
        if (rbd1.isSelected()) {
            int  iddoenc = 1;
            Doenca doe = new Doenca();  
              doe.setIddoencausu(iddoenc);
        }
        if (rbd2.isSelected()) {
            Doenca user = new Doenca();
          
              int  iddoenc = 2;
              user.setIddoencausu(iddoenc);
        }
        if (rbd3.isSelected()) {
            Doenca user = new Doenca();
          
              int  iddoenc = 3;
              user.setIddoencausu(iddoenc);
        }
        if (rbd4.isSelected()) {
            Doenca user = new Doenca();
           
              int  iddoenc = 4;
              user.setIddoencausu(iddoenc);
        }
        if (rbd5.isSelected()) {
            Doenca user = new Doenca();
           
              int  iddoenc = 5;
              user.setIddoencausu(iddoenc);
        }
        if (rbd6.isSelected()) {
            Doenca user = new Doenca();
           
              int  iddoenc = 6;
              user.setIddoencausu(iddoenc);
        }

        
        
        if (rbf1.isSelected()) {
            Dados user = new Dados();
            double sede = 1.20;
            user.setImcGeral(sede);
        }
        if (rbf2.isSelected()) {
            Dados user = new Dados();
            double pati = 1.37;
             user.setImcGeral(pati);
       }
        if (rbf3.isSelected()) {
            Dados user = new Dados();
            double ativo = 1.55;
            user.setImcGeral(ativo);
       }
        if (rbf4.isSelected()) {
            Dados user = new Dados();
            double mtati = 1.72;
        user.setImcGeral(mtati);
        }
        if (rbf5.isSelected()) {
            Dados user = new Dados();
            double diar = 1.90;
      user.setImcGeral(diar);
        }

        
        
         Doenca doe = new Doenca();
        if (rbp1.isSelected()) {
            String perder = "Perder peso";
            doe.setDado(perder);
        }
        if (rbp2.isSelected()) {
             String manter = "Manter peso";
            doe.setDado(manter);
        }
        if (rbp3.isSelected()) {
             String ganhar = "Ganhar peso";
            doe.setDado(ganhar);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rbd1 = new javax.swing.JRadioButton();
        rbd2 = new javax.swing.JRadioButton();
        rbd3 = new javax.swing.JRadioButton();
        rbd4 = new javax.swing.JRadioButton();
        rbd5 = new javax.swing.JRadioButton();
        rbd6 = new javax.swing.JRadioButton();
        rbf1 = new javax.swing.JRadioButton();
        rbf2 = new javax.swing.JRadioButton();
        rbf3 = new javax.swing.JRadioButton();
        rbf4 = new javax.swing.JRadioButton();
        rbf5 = new javax.swing.JRadioButton();
        rbp1 = new javax.swing.JRadioButton();
        rbp2 = new javax.swing.JRadioButton();
        rbp3 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Desktop = new javax.swing.JDesktopPane();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jLabel4.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Deseja");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(400, 90, 80, 18);

        jLabel3.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Ativi. Física");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(230, 90, 90, 18);

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Doença Alimentar:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 90, 120, 18);

        rbd1.setBackground(new java.awt.Color(102, 0, 204));
        rbd1.setForeground(new java.awt.Color(255, 255, 255));
        rbd1.setText("Sem doença");
        rbd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbd1ActionPerformed(evt);
            }
        });
        getContentPane().add(rbd1);
        rbd1.setBounds(50, 110, 85, 23);

        rbd2.setBackground(new java.awt.Color(102, 0, 204));
        rbd2.setForeground(new java.awt.Color(255, 255, 255));
        rbd2.setText("Gastrite");
        rbd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbd2ActionPerformed(evt);
            }
        });
        getContentPane().add(rbd2);
        rbd2.setBounds(50, 130, 63, 23);

        rbd3.setBackground(new java.awt.Color(102, 0, 204));
        rbd3.setForeground(new java.awt.Color(255, 255, 255));
        rbd3.setText("Diabetes");
        rbd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbd3ActionPerformed(evt);
            }
        });
        getContentPane().add(rbd3);
        rbd3.setBounds(50, 150, 67, 23);

        rbd4.setBackground(new java.awt.Color(102, 0, 204));
        rbd4.setForeground(new java.awt.Color(255, 255, 255));
        rbd4.setText("Obesidade");
        rbd4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbd4ActionPerformed(evt);
            }
        });
        getContentPane().add(rbd4);
        rbd4.setBounds(50, 170, 77, 23);

        rbd5.setBackground(new java.awt.Color(102, 0, 204));
        rbd5.setForeground(new java.awt.Color(255, 255, 255));
        rbd5.setText("Colesterol Alto");
        rbd5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbd5ActionPerformed(evt);
            }
        });
        getContentPane().add(rbd5);
        rbd5.setBounds(50, 190, 95, 23);

        rbd6.setBackground(new java.awt.Color(102, 0, 204));
        rbd6.setForeground(new java.awt.Color(255, 255, 255));
        rbd6.setText("Hipertensão");
        rbd6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbd6ActionPerformed(evt);
            }
        });
        getContentPane().add(rbd6);
        rbd6.setBounds(50, 210, 83, 23);

        rbf1.setBackground(new java.awt.Color(102, 0, 204));
        rbf1.setForeground(new java.awt.Color(255, 255, 255));
        rbf1.setText("Sedentário");
        rbf1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbf1ActionPerformed(evt);
            }
        });
        getContentPane().add(rbf1);
        rbf1.setBounds(230, 110, 77, 23);

        rbf2.setBackground(new java.awt.Color(102, 0, 204));
        rbf2.setForeground(new java.awt.Color(255, 255, 255));
        rbf2.setText("Pouco ativo");
        rbf2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbf2ActionPerformed(evt);
            }
        });
        getContentPane().add(rbf2);
        rbf2.setBounds(230, 130, 81, 23);

        rbf3.setBackground(new java.awt.Color(102, 0, 204));
        rbf3.setForeground(new java.awt.Color(255, 255, 255));
        rbf3.setText("Ativo");
        rbf3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbf3ActionPerformed(evt);
            }
        });
        getContentPane().add(rbf3);
        rbf3.setBounds(230, 150, 50, 23);

        rbf4.setBackground(new java.awt.Color(102, 0, 204));
        rbf4.setForeground(new java.awt.Color(255, 255, 255));
        rbf4.setText("Muito ativo");
        rbf4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbf4ActionPerformed(evt);
            }
        });
        getContentPane().add(rbf4);
        rbf4.setBounds(230, 170, 90, 23);

        rbf5.setBackground(new java.awt.Color(102, 0, 204));
        rbf5.setForeground(new java.awt.Color(255, 255, 255));
        rbf5.setText("Diariamente");
        rbf5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbf5ActionPerformed(evt);
            }
        });
        getContentPane().add(rbf5);
        rbf5.setBounds(230, 190, 90, 23);

        rbp1.setBackground(new java.awt.Color(102, 0, 204));
        rbp1.setForeground(new java.awt.Color(255, 255, 255));
        rbp1.setText("Perder peso");
        rbp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbp1ActionPerformed(evt);
            }
        });
        getContentPane().add(rbp1);
        rbp1.setBounds(400, 110, 84, 23);

        rbp2.setBackground(new java.awt.Color(102, 0, 204));
        rbp2.setForeground(new java.awt.Color(255, 255, 255));
        rbp2.setText("Manter peso");
        rbp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbp2ActionPerformed(evt);
            }
        });
        getContentPane().add(rbp2);
        rbp2.setBounds(400, 130, 85, 23);

        rbp3.setBackground(new java.awt.Color(102, 0, 204));
        rbp3.setForeground(new java.awt.Color(255, 255, 255));
        rbp3.setText("Ganhar peso");
        rbp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbp3ActionPerformed(evt);
            }
        });
        getContentPane().add(rbp3);
        rbp3.setBounds(400, 150, 88, 23);

        jButton1.setText("Voltar");
        getContentPane().add(jButton1);
        jButton1.setBounds(50, 260, 100, 30);

        jButton2.setText("Avançar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(410, 260, 100, 30);

        jLabel5.setFont(new java.awt.Font("Arial Black", 0, 30)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Dados");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(40, 30, 110, 40);

        jLabel1.setBackground(new java.awt.Color(102, 0, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Background (3).png"))); // NOI18N
        Desktop.add(jLabel1);
        jLabel1.setBounds(0, -90, 850, 510);

        getContentPane().add(Desktop);
        Desktop.setBounds(0, 0, 830, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbd2ActionPerformed
        rbd1.setSelected(false);
        rbd3.setSelected(false);
        rbd4.setSelected(false);
        rbd5.setSelected(false);
        rbd6.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_rbd2ActionPerformed

    private void rbf2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbf2ActionPerformed
        rbf1.setSelected(false);
        rbf3.setSelected(false);
        rbf4.setSelected(false);
        rbf5.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_rbf2ActionPerformed

    private void rbp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbp2ActionPerformed
        rbp1.setSelected(false);
        rbp3.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_rbp2ActionPerformed

    private void rbp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbp3ActionPerformed
        rbp2.setSelected(false);
        rbp1.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_rbp3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
add();

        rbd1.setVisible(false);
        rbd2.setVisible(false);
        rbd3.setVisible(false);
        rbd4.setVisible(false);
        rbd5.setVisible(false);
        rbd6.setVisible(false);
        rbf1.setVisible(false);
        rbf2.setVisible(false);
        rbf3.setVisible(false);
        rbf4.setVisible(false);
        rbf5.setVisible(false);
        rbp1.setVisible(false);
        rbp2.setVisible(false);
        rbp3.setVisible(false);
        jButton1.setVisible(false);
        jButton2.setVisible(false);

        ResultadoCalc sa = new ResultadoCalc();
        sa.setVisible(true);
        Desktop.add(sa);           // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void rbd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbd1ActionPerformed
      

        rbd2.setSelected(false);
        rbd3.setSelected(false);
        rbd4.setSelected(false);
        rbd5.setSelected(false);
        rbd6.setSelected(false);


    }//GEN-LAST:event_rbd1ActionPerformed

    private void rbp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbp1ActionPerformed
        rbp2.setSelected(false);
        rbp3.setSelected(false);// TODO add your handling code here:
    }//GEN-LAST:event_rbp1ActionPerformed

    private void rbd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbd3ActionPerformed
        rbd1.setSelected(false);
        rbd2.setSelected(false);
        rbd4.setSelected(false);
        rbd5.setSelected(false);
        rbd6.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_rbd3ActionPerformed

    private void rbd4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbd4ActionPerformed
        rbd1.setSelected(false);
        rbd2.setSelected(false);
        rbd3.setSelected(false);
        rbd5.setSelected(false);
        rbd6.setSelected(false);         // TODO add your handling code here:
    }//GEN-LAST:event_rbd4ActionPerformed

    private void rbd5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbd5ActionPerformed
        rbd1.setSelected(false);
        rbd2.setSelected(false);
        rbd3.setSelected(false);
        rbd4.setSelected(false);
        rbd6.setSelected(false);          // TODO add your handling code here:
    }//GEN-LAST:event_rbd5ActionPerformed

    private void rbd6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbd6ActionPerformed
        rbd1.setSelected(false);
        rbd2.setSelected(false);
        rbd3.setSelected(false);
        rbd4.setSelected(false);
        rbd5.setSelected(false);          // TODO add your handling code here:
    }//GEN-LAST:event_rbd6ActionPerformed

    private void rbf1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbf1ActionPerformed
        rbf2.setSelected(false);
        rbf3.setSelected(false);
        rbf4.setSelected(false);
        rbf5.setSelected(false);// TODO add your handling code here:
    }//GEN-LAST:event_rbf1ActionPerformed

    private void rbf3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbf3ActionPerformed
        rbf1.setSelected(false);
        rbf2.setSelected(false);
        rbf4.setSelected(false);
        rbf5.setSelected(false);          // TODO add your handling code here:
    }//GEN-LAST:event_rbf3ActionPerformed

    private void rbf4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbf4ActionPerformed
        rbf1.setSelected(false);
        rbf2.setSelected(false);
        rbf3.setSelected(false);
        rbf5.setSelected(false);          // TODO add your handling code here:
    }//GEN-LAST:event_rbf4ActionPerformed

    private void rbf5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbf5ActionPerformed
        rbf1.setSelected(false);
        rbf2.setSelected(false);
        rbf3.setSelected(false);
        rbf4.setSelected(false);          // TODO add your handling code here:
    }//GEN-LAST:event_rbf5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JRadioButton rbd1;
    private javax.swing.JRadioButton rbd2;
    private javax.swing.JRadioButton rbd3;
    private javax.swing.JRadioButton rbd4;
    private javax.swing.JRadioButton rbd5;
    private javax.swing.JRadioButton rbd6;
    private javax.swing.JRadioButton rbf1;
    private javax.swing.JRadioButton rbf2;
    private javax.swing.JRadioButton rbf3;
    private javax.swing.JRadioButton rbf4;
    private javax.swing.JRadioButton rbf5;
    private javax.swing.JRadioButton rbp1;
    private javax.swing.JRadioButton rbp2;
    private javax.swing.JRadioButton rbp3;
    // End of variables declaration//GEN-END:variables
}
