/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Home;

import Classes.Conexao;
import Classes.Doenca;
import Classes.Usuario;
import java.sql.Connection;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author marcelo_eger
 */
public class CadastroAlimento extends javax.swing.JInternalFrame {
Connection conexao = null;
    PreparedStatement pst = null;
    /**
     * Creates new form CadastroAlimento
     */
    public CadastroAlimento() {
        initComponents();
        setSize(650, 400);
        conexao = Conexao.conector();
    }
private void adicionaralimento() {
        String sql = "insert into alimentos(doenca_iddoenca,descricao) values(?,?)";
   

      //  Usuario user = new Usuario();
     //   user.setNm_user(jTextField5.getText());
      //  user.setDs_password(jTextField1.getText());
       
   //     if (user.getNm_user().equals("")) {
  //          JOptionPane.showMessageDialog(null, "Preencha todos os campos obrigatórios");
    //    } else {

            try {
                pst = conexao.prepareStatement(sql);
                
                if(rbsemdo.isSelected()){
                  int  iddoenc = 1;
                  
                      pst.setInt(1, iddoenc);  
                      pst.setString(2, jTextField1.getText());
                }
                
                if(rbgas.isSelected()){
                  int  iddoenc = 2;
                  
                      pst.setInt(1, iddoenc); 
                      pst.setString(2, jTextField1.getText());
                }
                
                if(rbdia.isSelected()){
                  int  iddoenc = 3;
                      pst.setInt(1, iddoenc);  
                      pst.setString(2, jTextField1.getText());
                }
                
                if(rbobe.isSelected()){
                  int  iddoenc = 4;
                  
                      pst.setInt(1, iddoenc);  
                      pst.setString(2, jTextField1.getText());
                }
                
                if(rbcol.isSelected()){
                  int  iddoenc = 5;
                   
                      pst.setInt(1, iddoenc); 
                      pst.setString(2, jTextField1.getText());
                }
                
                if(rbhipe.isSelected()){
                  int  iddoenc = 6;
                 
                      pst.setInt(1, iddoenc);  
                      pst.setString(2, jTextField1.getText());
                }
              
                
             

                int adicionado = pst.executeUpdate();

                if (adicionado > 0) {
                    JOptionPane.showMessageDialog(null, "Cadastro realizado com sucesso");
                } else {
                    JOptionPane.showMessageDialog(null, "Ha um erro na inserção");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);

            
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        rbcol = new javax.swing.JRadioButton();
        rbhipe = new javax.swing.JRadioButton();
        rbdia = new javax.swing.JRadioButton();
        rbobe = new javax.swing.JRadioButton();
        rbgas = new javax.swing.JRadioButton();
        rbsemdo = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        desktop = new javax.swing.JDesktopPane();

        getContentPane().setLayout(null);

        rbcol.setBackground(new java.awt.Color(102, 0, 204));
        rbcol.setForeground(new java.awt.Color(255, 255, 255));
        rbcol.setText("Colesterol alto");
        rbcol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbcolActionPerformed(evt);
            }
        });
        getContentPane().add(rbcol);
        rbcol.setBounds(340, 70, 110, 30);

        rbhipe.setBackground(new java.awt.Color(102, 0, 204));
        rbhipe.setForeground(new java.awt.Color(255, 255, 255));
        rbhipe.setText("Hipertensão");
        rbhipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbhipeActionPerformed(evt);
            }
        });
        getContentPane().add(rbhipe);
        rbhipe.setBounds(450, 70, 100, 30);

        rbdia.setBackground(new java.awt.Color(102, 0, 204));
        rbdia.setForeground(new java.awt.Color(255, 255, 255));
        rbdia.setText("Diabetes");
        rbdia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbdiaActionPerformed(evt);
            }
        });
        getContentPane().add(rbdia);
        rbdia.setBounds(180, 70, 80, 30);

        rbobe.setBackground(new java.awt.Color(102, 0, 204));
        rbobe.setForeground(new java.awt.Color(255, 255, 255));
        rbobe.setText("Obesidade");
        rbobe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbobeActionPerformed(evt);
            }
        });
        getContentPane().add(rbobe);
        rbobe.setBounds(260, 70, 90, 30);

        rbgas.setBackground(new java.awt.Color(102, 0, 204));
        rbgas.setForeground(new java.awt.Color(255, 255, 255));
        rbgas.setText("Gastrite");
        rbgas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbgasActionPerformed(evt);
            }
        });
        getContentPane().add(rbgas);
        rbgas.setBounds(110, 70, 80, 30);

        rbsemdo.setBackground(new java.awt.Color(102, 0, 204));
        rbsemdo.setForeground(new java.awt.Color(255, 255, 255));
        rbsemdo.setText("Sem doença");
        rbsemdo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbsemdoActionPerformed(evt);
            }
        });
        getContentPane().add(rbsemdo);
        rbsemdo.setBounds(10, 70, 100, 30);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Escolha umas das doenças para cadastar as comidas");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 40, 450, 21);

        jButton1.setText("Avançar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(430, 250, 100, 30);

        jButton2.setText("Voltar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(30, 250, 100, 30);
        getContentPane().add(jTextField1);
        jTextField1.setBounds(50, 170, 370, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Informe o nome da comida");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 150, 230, 14);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Background (3).png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, -160, 559, 650);
        getContentPane().add(desktop);
        desktop.setBounds(0, 10, 630, 350);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbsemdoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbsemdoActionPerformed
 rbgas.setSelected(false);   
  rbdia.setSelected(false); 
 rbobe.setSelected(false); 
 rbcol.setSelected(false); 
 rbhipe.setSelected(false); // TODO add your handling code here:
    }//GEN-LAST:event_rbsemdoActionPerformed

    private void rbobeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbobeActionPerformed
rbsemdo.setSelected(false);   
  rbdia.setSelected(false); 
 rbgas.setSelected(false); 
 rbcol.setSelected(false); 
 rbhipe.setSelected(false);         // TODO add your handling code here:
    }//GEN-LAST:event_rbobeActionPerformed

    private void rbcolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbcolActionPerformed
rbsemdo.setSelected(false);   
  rbdia.setSelected(false); 
 rbgas.setSelected(false); 
 rbobe.setSelected(false); 
 rbhipe.setSelected(false);         // TODO add your handling code here:
    }//GEN-LAST:event_rbcolActionPerformed

    private void rbhipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbhipeActionPerformed
rbsemdo.setSelected(false);   
  rbdia.setSelected(false); 
 rbgas.setSelected(false); 
 rbobe.setSelected(false); 
 rbcol.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_rbhipeActionPerformed

    private void rbgasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbgasActionPerformed
 rbsemdo.setSelected(false);   
  rbdia.setSelected(false); 
 rbobe.setSelected(false); 
 rbcol.setSelected(false); 
 rbhipe.setSelected(false);        // TODO add your handling code here:
    }//GEN-LAST:event_rbgasActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        SA sa = new SA();
        sa.setVisible(true);
        desktop.add(sa);
// TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
adicionaralimento(); 
        jButton1.setVisible(false);
        rbobe.setVisible(false);
        rbsemdo.setVisible(false);
        rbgas.setVisible(false);
        rbcol.setVisible(false);
        rbhipe.setVisible(false);
        rbdia.setVisible(false);
        CadastroAli2 sa = new CadastroAli2();
        sa.setVisible(true);
        desktop.add(sa);      // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rbdiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbdiaActionPerformed
rbsemdo.setSelected(false);   
  rbgas.setSelected(false); 
 rbobe.setSelected(false); 
 rbcol.setSelected(false); 
 rbhipe.setSelected(false);         // TODO add your handling code here:
    }//GEN-LAST:event_rbdiaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton rbcol;
    private javax.swing.JRadioButton rbdia;
    private javax.swing.JRadioButton rbgas;
    private javax.swing.JRadioButton rbhipe;
    private javax.swing.JRadioButton rbobe;
    private javax.swing.JRadioButton rbsemdo;
    // End of variables declaration//GEN-END:variables
}
